### ISSUE TITLE
Whitespace in translation values

### ISSUE THREAD

**Issue by wmaurer** [Lambda-IT/ng-translate#1]
It would be nice if the translated values that are extracted from the inner html would be stripped of whitespace and \r\n characters. This would reduce the size of the translations json.

**Comment by wmaurer** [comment]
As discussed, maybe we could have an extra attribute to preserve whitespace for the special cases where it might be needed, e.g. in a textarea control.

**Comment by Lambda-IT** [comment]
moved to gulp-angular-translate-parse...
